format_code_in_doc_comments = true
format_macro_matchers       = true
format_strings              = true
imports_granularity         = "One"
#imports_granularity = "Module"
normalize_doc_attributes    = true
tab_spaces                  = 2
unstable_features           = true
#
edition = "2021"
max_width = 120
# max_width = 80
use_small_heuristics = "Max"
use_field_init_shorthand = true
match_arm_leading_pipes = "Preserve"
#
group_imports = "StdExternalCrate"
reorder_impl_items = true
