edition = "2021"
max_width = 100
use_small_heuristics = "Max"
newline_style = "Unix"
tab_spaces = 4
hard_tabs = false
wrap_comments = true
format_code_in_doc_comments = true
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
reorder_imports = true
reorder_modules = true
normalize_comments = true
normalize_doc_attributes = true
format_strings = true
struct_field_align_threshold = 20
fn_single_line = false
where_single_line = false
match_block_trailing_comma = true
trailing_comma = "Always"
merge_derives = true
blank_lines_upper_bound = 2
blank_lines_lower_bound = 0
comment_width = 80
